service: calorie-tracker-sls
frameworkVersion: '2'
plugins:
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-reqvalidator-plugin
  - serverless-domain-manager
provider:
  name: aws
  runtime: java11
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  memorySize: ${env:SLS_PROVIDER_MEMSIZE}
  timeout: 30
  region: ${env:SLS_PROVIDER_REGION}
  logs:
    restApi: true
  tracing:
    lambda: ${env:SLS_LAMBDA_TRACING}

  # you can define service wide environment variables here
  environment:
    DRASH_AWS_REGION: ${self:provider.region}
    DRASH_AWS_COGNITO_USERPOOL_ID: !Ref CognitoUserPool
    DRASH_AWS_ACCOUNT_ID: !Ref AWS::AccountId
    DRASH_AWS_IDENTITY_POOL_ID: !Ref CognitoIdentityPool
    DRASH_DEPLOYMENT_STAGE: ${self:provider.stage}
    DRASH_TABLE_NAME: ${self:custom.ottoTableName}
    DRASH_EVENT_BUS_NAME: ${self:custom.eventBus}
    DRASH_EVENT_SOURCE: ${self:custom.eventSource}


package:
  individually: true

functions:

resources:
  - ${file(serverless-resources/dynamodb.yml)}
  - ${file(serverless-resources/roles.yml)}
  - ${file(serverless-resources/request-validator.yml)}



